default:
  tags:
    - bs-runner-2

stages:
  - test
  - build
  - deploy
  - quality

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
#   PLATFORMS: linux/amd64,linux/arm64

test-units:
  stage: test
  image: composer:2
  script:
    - composer install --ignore-platform-reqs
  allow_failure: true

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE dev/docker
    - docker push $IMAGE

deploy:
  stage: deploy
  script:
    - echo "déploiement au sprint1"

quality:
  stage: quality
  image: sonarsource/sonar-scanner-cli:12.1
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: true
