services:
  bookstack:
    image: registry.gitlab.com/capsule-bookstack/bookstack:f1bf8f4d
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://bookstack-alb-2030915568.eu-north-1.elb.amazonaws.com
      - DB_CONNECTION=mysql
      - DB_HOST=shared-bookstack-keycloak-rds.crogwcggglt8.eu-north-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=bookstack_production
      - DB_USERNAME=dbadmin
      - DB_PASSWORD=bsCapsRdsPwd
      - APP_KEY=base64:71iz6TD94TrxLUohQmwVYkRuVs5SiB95C1qTsAog4aY=
      # - STORAGE_TYPE=s3
      # - STORAGE_S3_KEY=votre_access_key_id
      # - STORAGE_S3_SECRET=votre_secret_access_key
      # - STORAGE_S3_BUCKET=nom-de-votre-bucket
      # - STORAGE_S3_REGION=eu-north-1
    ports:
      - "6875:80"
    volumes:
      - bookstack_config:/config
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager

volumes:
  bookstack_config:
