sonar.projectKey=capsule-bookstack_bookstack
sonar.organization=capsule-bookstack
sonar.sourceEncoding=UTF-8

# Répertoires à analyser
sonar.sources=app,resources,public

# Répertoires à exclure (gros gain de perf)
sonar.exclusions=\
  **/vendor/**,\
  **/node_modules/**,\
  **/storage/**,\
  **/public/uploads/**,\
  **/*.md,\
  **/*.lock,\
  **/*.min.js,\
  **/*.min.css

# Désactiver les langages inutiles (gros gain de perf)
sonar.css.file.suffixes=-
sonar.yaml.file.suffixes=-
sonar.xml.file.suffixes=-
sonar.json.file.suffixes=-
sonar.shell.file.suffixes=-
sonar.docker.file.suffixes=-
sonar.iac.file.suffixes=-

# Forcer l'utilisation du Node local (évite les crashs)
sonar.nodejs.executable=/usr/bin/node

# Optimisation GitLab CI
sonar.scm.provider=git
